import { Router, type IRouter } from "express";
import healthRouter from "./health";
import productsRouter from "./products";
import suppliersRouter from "./suppliers";
import ordersRouter from "./orders";
import dashboardRouter from "./dashboard";
import researchRouter from "./research";
import supplierFinderRouter from "./supplier-finder";
import priceWatchRouter from "./price-watch";
import reportsRouter from "./reports";
import customerInsightsRouter from "./customer-insights";
import purchaseOrdersRouter from "./purchase-orders";
import returnsRouter from "./returns";
import orderTimelineRouter from "./order-timeline";
import promotionsRouter from "./promotions";
import productTagsRouter from "./product-tags";
import cashFlowRouter from "./cash-flow";
import productScorerRouter from "./product-scorer";
import rfmRouter from "./rfm";
import launchesRouter from "./launches";
import adCampaignsRouter from "./ad-campaigns";
import storeConnectionsRouter from "./store-connections";
import aiSettingsRouter from "./ai-settings";
import fulfillmentRouter from "./fulfillment";

const router: IRouter = Router();

router.use(healthRouter);
router.use(productsRouter);
router.use(supplierFinderRouter);
router.use(suppliersRouter);
router.use(customerInsightsRouter);
router.use(ordersRouter);
router.use(dashboardRouter);
router.use(researchRouter);
router.use(priceWatchRouter);
router.use(reportsRouter);
router.use(purchaseOrdersRouter);
router.use(returnsRouter);
router.use(orderTimelineRouter);
router.use(promotionsRouter);
router.use(productTagsRouter);
router.use(cashFlowRouter);
router.use(storeConnectionsRouter);
router.use(productScorerRouter);
router.use(rfmRouter);
router.use(launchesRouter);
router.use(adCampaignsRouter);
router.use(aiSettingsRouter);
router.use(fulfillmentRouter);

export default router;
